# Site settings

title: Mokammel Haque Heerat
description: Computer Science & Engineering Student | Aspiring Software Developer

# Theme settings

remote_theme: pages-themes/cayman@v0.2.0
plugins:

* jekyll-remote-theme

# Show download button (optional)

show_downloads: false

# GitHub Pages settings

github:
is_project_page: true

# Markdown & build settings

markdown: kramdown
kramdown:
input: GFM

# Exclude unnecessary files

exclude:

* README.md
* Gemfile
* Gemfile.lock
* node_modules
* vendor
