# ----------------------------

# Site Configuration

# ----------------------------

title: Mokammel Haque Heerat
description: Computer Science & Engineering Student | Aspiring Software Developer

# ----------------------------

# Theme Configuration

# ----------------------------

remote_theme: pages-themes/cayman@v0.2.0
plugins:

* jekyll-remote-theme

# ----------------------------

# GitHub Pages Settings

# ----------------------------

show_downloads: false

github:
is_project_page: true

# ----------------------------

# Markdown & Build Settings

# ----------------------------

markdown: kramdown
kramdown:
input: GFM

# ----------------------------

# Excluded Files

# ----------------------------

exclude:

* README.md
* Gemfile
* Gemfile.lock
* node_modules
* vendor
